default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: raty_development

test:
  <<: *default
  database: raty_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: myapp_production
  username: myapp
  password: <%= ENV['RATY_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock

